### PR TITLE
[OP-227] Update to Java 8

### PR DESCRIPTION
**Pull request by larsgrefer**
This PR updates the bundled JRE versions:

Windows: AdoptOpenJDK jdk8u252-b09.1 (x86)
Linux-32: Azul Zulu 8.46.0.19 (8u252b14)
Linux-64: AdoptOpenJDK jdk8u252-b09

### CODE REVIEW

**Comment by larsgrefer** [comment]
It seems like there is no 32 bit JRE for linux.

**Comment by larsgrefer** [comment]
Azul still provides a 32 bit JRE 👍

**Review by pviotti — COMMENTED** [review]
What about downloading the JREs during the build process (and checking its checksum), so that we don't have to keep all those files we don't "own" in this repo?  
I believe part of the reason we didn't do this when we created this repo about one year ago, was that some artifacts were difficult to retrieve (e.g. that old version of MySQL - which we should upgrade, and java6 32bit). But for JRE 8 there shouldn't be any problem to download it with `curl` or `wget`.

Other than that, it looks good - I'll check the build more carefully in the next days.

**Comment by mwithi** [comment]
For the MySQL binaries we can also download them. Yes, the main reason we were keeping them was the compliance with previous versions.

Also, today I was thinking if we really need gitmodules since we can also clone on the fly the desidered repos. What do you think about it?

**Comment by larsgrefer** [comment]
Downloading the MySQL binaries sounds good, but should be handled in a different PR.

No, you don't need submodules 😅 My opinion about the submodules is already documented in #73

**Comment by pviotti** [comment]
Submodules are git's way of handling external dependencies, but indeed in this case they don't provide significative benefits wrt to just cloning and checking out a tag. I'll create an issue and give it a shot.  
This PR looks good (I only tried the Linux x64 version though), thanks Lars.

**Review by pviotti — APPROVED** [review]

**Comment by mwithi** [comment]
Sorry guys, been busy for many days.

> Downloading the MySQL binaries sounds good, but should be handled in a different PR.

I agree.

> No, you don't need submodules 😅 My opinion about the submodules is already documented in #73 

Yes I remember, but I mean something different: still keeping separated repositories for each component and using this repo for building the releases only. As I think @pviotti is doing in https://github.com/informatici/openhospital/issues/122

**Review by mwithi — COMMENTED** [review]
It looks good, nevertheless I think that this merge cannot be independent from changing also https://github.com/informatici/openhospital-core and https://github.com/informatici/openhospital-gui.

I've created OP-224 and this PR is sub-task OP-227.
So we need to parallel OP-225 and OP-226.

What do you think?

**Comment by pviotti** [comment]
> What do you think?

I think it's good to group those tasks together, but this PR can be merged independently of all other OPs related to core and gui. 
Also because which Java bytecode version is used in each project is defined in each project's pom.xml file, respectively
here https://github.com/informatici/openhospital-gui/blob/develop/pom.xml#L30
and here https://github.com/informatici/openhospital-core/blob/develop/pom.xml#L29
And anyway AFAIK Java 8 can compile to and execute Java 6 bytecode.

**Comment by larsgrefer** [comment]
@pviotti Both JDK 8 and even JDK 11 can still compile to 1.6 bytecode. And they can both execute even older bytecode.

**Comment by mwithi** [comment]
> And anyway AFAIK Java 8 can compile to and execute Java 6 bytecode.

> @pviotti Both JDK 8 and even JDK 11 can still compile to 1.6 bytecode. And they can both execute even older bytecode.

yep, the point here is to not only changing the JRE but also apply the good-practises introduces by each JDK into the code and test them. Under this perspective https://github.com/informatici/openhospital/pull/125 could hold a bit, wdyt? My fear is that differences would be too many with JDK6 and then lead to unexpected behaviors (like it actually happens for gui, as example https://openhospital.atlassian.net/browse/OP-226)

**Pull request merged**
