### PR TITLE
OP-558 - settings file update 

### PR DESCRIPTION
**Pull request by mizzioisf**
See https://openhospital.atlassian.net/browse/OP-558
I have also updated the script files and external software (mariadb) versions accordingly.

### CODE REVIEW

**Review by mwithi — COMMENTED** [review]
Despite checks fail, the merge will be ok (only need to checkout last develop instead of tag 1.11, that is old).
However, when I run oh.bat it hangs at `Starting Open Hospital...` and in the `mysql.err.log` there is:
```
2021-07-21  8:53:20 11380 [Note] InnoDB: Cannot open 'D:\OpenHospital_versions\poh-win32-0.1-core-develop\data\db\ib_buffer_pool' for reading: No such file or directory
2021-07-21  8:53:20 10044 [Note] Plugin 'FEEDBACK' is disabled.
2021-07-21  8:53:20 10044 [ERROR] Could not open mysql.plugin table. Some plugins may be not loaded
2021-07-21  8:53:20 10044 [ERROR] Can't open and lock privilege tables: Table 'mysql.servers' doesn't exist
2021-07-21  8:53:20 10044 [Note] Server socket created on IP: '::1'.
2021-07-21  8:53:20 10044 [ERROR] Fatal error: Can't open and lock privilege tables: Table 'mysql.user' doesn't exist
``` 
PS: disabled antivirus, firewall and other MySQL istances

After a clean (X) it works fine... maybe something in the original files that are included during make file package (e.g. `database.properties`)?

**Comment by mwithi** [comment]
Yeah, I think that is the problem: `settings.properties`, `database.properties`, `log4j.properties`, and `dicom.properties` are already in place coming from "gui" project, we should exclude those when packaging portable with Makefile because they will be created from related `.dist` otherwise a "clean" before to start poh might be needed

OR

we could move `.dist` files into "gui" project (and so remove them from `poh-bundle-*`) although in this way devs cloning "core"+"gui" should create `.properties` from `.dist` by themselves (needs instructions in README)

**Comment by mizzioisf** [comment]
> Despite checks fail, the merge will be ok (only need to checkout last develop instead of tag 1.11, that is old).
> However, when I run oh.bat it hangs at `Starting Open Hospital...` and in the `mysql.err.log` there is:
> 
> ```
> 2021-07-21  8:53:20 11380 [Note] InnoDB: Cannot open 'D:\OpenHospital_versions\poh-win32-0.1-core-develop\data\db\ib_buffer_pool' for reading: No such file or directory
> 2021-07-21  8:53:20 10044 [Note] Plugin 'FEEDBACK' is disabled.
> 2021-07-21  8:53:20 10044 [ERROR] Could not open mysql.plugin table. Some plugins may be not loaded
> 2021-07-21  8:53:20 10044 [ERROR] Can't open and lock privilege tables: Table 'mysql.servers' doesn't exist
> 2021-07-21  8:53:20 10044 [Note] Server socket created on IP: '::1'.
> 2021-07-21  8:53:20 10044 [ERROR] Fatal error: Can't open and lock privilege tables: Table 'mysql.user' doesn't exist
> ```
> 
> PS: disabled antivirus, firewall and other MySQL istances
> 
> After a clean (X) it works fine... maybe something in the original files that are included during make file package (e.g. `database.properties`)?

You need to clean the installation before launching oh.bat, that's the cause of the error.

**Comment by mizzioisf** [comment]
> Yeah, I think that is the problem: `settings.properties`, `database.properties`, `log4j.properties`, and `dicom.properties` are already in place coming from "gui" project, we should exclude those when packaging portable with Makefile because they will be created from related `.dist` otherwise a "clean" before to start poh might be needed
> 
> OR
> 
> we could move `.dist` files into "gui" project (and so remove them from `poh-bundle-*`) although in this way devs cloning "core"+"gui" should create `.properties` from `.dist` by themselves (needs instructions in README)

I'm planning to review the packaging part in order to simplify things overcome these issues; I think we can leave instructions in the README for the devs. Yes, we need to package only the dist files for the users.

**Comment by mwithi** [comment]
Ok, let's do it in OP-343

**Pull request merged**
