### PR TITLE
OP-315 - Updated oh.sh

### PR DESCRIPTION
**Pull request by mizzioisf**
**Updated 2020.11.16**

In order to have a complete, easy to support and extensible solution to OP-223 and also OP-218, and following #138  and #142  I have basically rewritten oh.sh, also adding a few possible useful user functions.
Note: the pull requires this code (https://github.com/informatici/openhospital-core/pull/241) related to OP-344 to be merged in order to expose all functionalities (demo mode in particular).

I have widely tested it and it seems to be working well (Ubuntu 20.04 64bit), solving also a few old outstanding bugs (mysql not always starting or shutting down, wrong socket references, hard coded values, etc. etc.)

Description of changes:
- Complete overhaul of the code, reworked the entire script
- Everything is now function based
- Menu based, interactive options for many operations: see **./oh.sh -h** (or below for short description)
- **Unified script** for:
    Portable 64bit (default) and 32bit (with automatic architecture detection)
    Open Hospital client (no more separated startup.sh is needed ;-) (**it is now possible to package every linux distro, client/portable/32 or 64 bit with a single package**)
- **New**: Language support (both via variable in the script or user input option: **oh.sh -l fr**)
- **New**: Demo database support -> depends on this -> https://github.com/informatici/openhospital-core/pull/241
- **New**: GSM setup integrated via -G command line option - setupGSM.sh (https://github.com/informatici/openhospital-gui/blob/develop/SetupGSM.sh) is obsolete now
- **New**: debug mode -> set log4.properties to DEBUG mode (default is INFO)
- Centralized variable managing (see related config file changes applied): now all (well, almost all, still some "isf" reference in SQL creation script...that will be removed ;-) references to database password, mysql host, etc. etc. are in the script and can be easily adapted / modified for any need
- More flexible execution and configuration options
- Automation of configuration files generation
- Everything is commented in the code and a brief output all operations is shown in console
- Backward compatible with old versions and installations, no default behaviour change
- Added sql subdirectory to organize sql scripts
- Added various checks about correct settings of parameters and startup of services
- Added security controls (no more _rm -rf_ here and there :-)
- Added support for **MariaDB** - (tested with mariadb-10.2.36-linux-x86_64) (POH seems faster and more responsive)
- Updated MySQL db and user creation syntax (now compatible with MySQL 8 - unsupported)
- Fixed _a_few_ bugs ;-)

Still working on:
- Small fixes ad modification: I will be still add few commits in next days

Will update Admin Manual accordingly after OP-223 and OP-218 are completed.

Feel free to comment ad add suggestions !

--------------------

```
 Portable Open Hospital Client - OH

 Usage: oh.sh [-option]

   -l    en|fr|it|es|pt   --> set language [default: oh.sh -l en]

   -s    save OH database
   -r    restore OH database
   -c    clean POH installation
   -d    start POH in debug mode
   -C    start Open Hospital - Client / Server mode
   -t    test database connection (Client mode only)
   -v    show POH version information
   -D    start POH in Demo mode
   -G    Setup GSM
   -h    show this help


```

### CODE REVIEW

**Comment by mizzioisf** [comment]
To review

**Comment by rospus** [comment]
> **Updated 2020.11.16**
> ... 
> Feel free to comment ad add suggestions !

Here is my report (ubuntu 20.04 LTS): 

- The presence of openjdk1.8.0 was not recognized and the script proceeded to install 1.11.0 `Warning - JAVA not found. Do you want to download it? (50 MB)`. If 1.11.0 is needed there should be a comment for the user.
- Error Initializing MySQL database on port 3307 `error while loading shared libraries: libaio.so.1`. I had to install it manually and re-launch the script.
- Error on creating OH Database `error while loading shared libraries: libncurses.so.5`. I had to install it manually and re-launch the script.
- Error while OH start that caused exit and MySQL shutdown:

> _Starting Open Hospital...
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (file:/home/rospus/Scrivania/OH_mizziotest/poh-1.11.beta/oh/lib/spring-core-4.3.28.RELEASE.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
java.lang.reflect.InvocationTargetException
	at java.desktop/java.awt.EventQueue.invokeAndWait(Unknown Source)
	at java.desktop/java.awt.EventQueue.invokeAndWait(Unknown Source)
	at java.desktop/javax.swing.SwingUtilities.invokeAndWait(Unknown Source)
	at org.isf.menu.gui.SplashWindow3$3.run(SplashWindow3.java:85)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at org.isf.menu.gui.MainMenu.<init>(MainMenu.java:205)
	at org.isf.menu.gui.SplashWindow3$2.run(SplashWindow3.java:75)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at org.isf.utils.jobjects.WaitCursorEventQueue.dispatchEvent(WaitCursorEventQueue.java:51)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Exiting Open Hospital...
Shutting down MySQL..._

**Comment by mizzioisf** [comment]
Ciao Rospus, thank you for the test !

quick reply:

- For this error: error while loading shared libraries: libaio.so.1.try this:
https://askubuntu.com/questions/886589/cannot-install-mysql-libaio-so-1-cannot-open-shared-object-file-no-such-file

```
sudo /etc/init.d/apparmor stop
sudo /etc/init.d/apparmor teardown
sudo update-rc.d -f apparmor remove

```
or also:

`sudo apt-get purge apparmor`

For the the JDK 8, do you have it installed system-wide ? If this is the case, you have to uncomment the "JAVA_BIN=..." line in the script. Otherwise the script will look for the jdk just in the current POH directory.

For the ncurses error, this sounds really strange: do you have ncurses installed ? if not, can you try:

`sudo apt-get install libncurses5` 
or
`apt-get install ncurses-compat-libs`

so we can understand if the problem is there ?

Thank you !!!

**Comment by rospus** [comment]
I was already aware of that link with the apparmor problem, I tried it and in my case it didn't work so I had to install libaio.so.1 manually to continue, as stated in my previous message.
Same thing for libncurses.so.5 and after relaunching the script I'm stuck with the java warning.
The three errors were subordinate.

**Comment by mizzioisf** [comment]
can you try pls:

oh.sh -c (to clean installation)
oh.sh (to relaunch installation)

**Comment by rospus** [comment]
Installation cleaned and erased all the files.
Done a new installation and got through (libraries were already installed), OH launched and it works (I did some editing) but with the following warning:

> _Starting Open Hospital...
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (file:/home/rospus/Scrivania/OH_mizziotest/poh-1.11.beta/oh/lib/spring-core-4.3.28.RELEASE.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
> WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release_

Seems like it's java >9 related, here some clues: [https://stackoverflow.com/questions/50251798/what-is-an-illegal-reflective-access](url)

image

**Comment by mizzioisf** [comment]
Thank you !
Yes, I have the same warning - and BTW there is no way of hiding out that output from console whatsoever.

**Comment by mwithi** [comment]
The warning is related to Spring4, I would not care about it too much because we are bumping to Spring5 soon.
For the missing libraries in some Linux distro what about adding a note in the docs?

**Comment by rospus** [comment]
I did some research and it seems like the presence of these libraries is quite eterogeneous within Linux distros.
I agree it's a good idea to put a note in the docs just mentioning that some libraries could be missing.
Also in the script error message it could be added some text warning to install manually the missing library and re-launch the installer.

**Comment by mizzioisf** [comment]
Yes we can put a reference in the documentation. It's not easy to check the presence of those libraries in the script, since they are system wide libs.

**Comment by mizzioisf** [comment]
> Installation cleaned and erased all the files.
> Done a new installation and got through (libraries were already installed), OH launched and it works (I did some editing) but with the following warning:
> 
> > _Starting Open Hospital...
> > WARNING: An illegal reflective access operation has occurred
> > WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (file:/home/rospus/Scrivania/OH_mizziotest/poh-1.11.beta/oh/lib/spring-core-4.3.28.RELEASE.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
> > WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
> > WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> > WARNING: All illegal access operations will be denied in a future release_
> 
> Seems like it's java >9 related, here some clues: [https://stackoverflow.com/questions/50251798/what-is-an-illegal-reflective-access](url)
> 
> image

The console warning is now redirected to startup.log file, see latest 315 pull request.

**Pull request merged**
